services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:3000/api
      NEXT_PUBLIC_SHOW_SIDEBAR: "true"
    restart: always
